---
name: Docker Image CI
on:
  push:
    branches:
      - "*"
    paths:
      - /docker1
  pull_request:
    branches:
      - "*"
    paths:
      - /docker1
    base:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        working-directory: /docker1
        run: |
          docker build . --file Dockerfile --tag image1:${{ github.sha }}
          docker run image1:${{ github.sha }}
