name: Docker Image Build Test - docker3
on:
  push:
    branches:
      - "*"
    paths:
      - "docker3/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "docker3/**"

jobs:
  check_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Dockerfile
        id: check_dockerfile
        run: |
          if [ -f "docker3/Dockerfile" ]; then
            echo "Dockerfile found"
            echo "BUILD_DOCKER=true" >> $GITHUB_ENV
          else
            echo "Dockerfile not found"
            echo "BUILD_DOCKER=false" >> $GITHUB_ENV
          fi

  build:
    runs-on: ubuntu-latest
    needs: check_dockerfile
    if: env.BUILD_DOCKER == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          cd docker3
          docker build . --file Dockerfile --tag image3:${{ github.sha }}
          docker run image3:${{ github.sha }}
