---
name: Docker Image Build Test - docker1
on:
  push:
    branches:
      - "*"
    paths:
      - "docker1/**"
  pull_request:
    branches:
      - "*"
    paths:
      - "docker1/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check for Dockerfile
        run: |
          if [ -f "docker1/Dockerfile" ]; then
            echo "Dockerfile found"
            echo "BUILD_DOCKER=true" >> $GITHUB_ENV
          else
            echo "Dockerfile not found"
            echo "BUILD_DOCKER=false" >> $GITHUB_ENV
          fi
      - name: Build the Docker image
        if: ${{ env.BUILD_DOCKER }} == 'true'
        run: |
          cd docker1
          docker build . --file Dockerfile --tag image1:${{ github.sha }}
          docker run image1:${{ github.sha }}
